name: Playwright Tests

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - run-playwright

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print PR Number
        run: |
          echo "PR Number = ${{ github.event.client_payload.pr_number }}"

      - name: Check PAT
        env:
          GH_TOKEN: ${{ secrets.PLAYWRIGHT_PAT }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "PLAYWRIGHT_PAT is missing!"
            exit 1
          fi

          echo "PAT Loaded Successfully"

      - name: Get PR Details
        env:
          GH_TOKEN: ${{ secrets.PLAYWRIGHT_PAT }}
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/j3-m2stack/angular_dashboard_1/pulls/${{ github.event.client_payload.pr_number }} \
            -o pr.json

          echo "========== PR DETAILS =========="
          cat pr.json

      - name: Get Deployments
        env:
          GH_TOKEN: ${{ secrets.PLAYWRIGHT_PAT }}
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/j3-m2stack/angular_dashboard_1/deployments \
            -o deployments.json

          echo "========== DEPLOYMENTS =========="
          cat deployments.json

      - name: Get Deployment Status
        env:
          GH_TOKEN: ${{ secrets.PLAYWRIGHT_PAT }}
        run: |
          DEPLOYMENT_ID=$(jq -r '.[0].id' deployments.json)

          echo "Deployment ID: $DEPLOYMENT_ID"

          if [ "$DEPLOYMENT_ID" = "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
            echo "No deployment found!"
            exit 1
          fi

          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/j3-m2stack/angular_dashboard_1/deployments/$DEPLOYMENT_ID/statuses \
            -o deployment-status.json

          echo "========== DEPLOYMENT STATUS =========="
          cat deployment-status.json

      - name: Get Netlify Preview URL
        run: |
          DEPLOY_URL=$(jq -r '.statuses[] | .target_url' status.json)

          echo "Deploy URL: $DEPLOY_URL"

          if [ -z "$DEPLOY_URL" ] || [ "$DEPLOY_URL" = "null" ]; then
            echo "Netlify Deploy Preview URL not found!"
            exit 1
          fi

          echo "BASE_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: |
          echo "Running on $BASE_URL"
          npx playwright test

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report